#!/usr/bin/env bash
echo "======== date ======="
echo -e "Day"
echo -e "\t A = $(date +"%A (a = %a)")"
echo -e "\t d = $(date +"%d (e = \"%e\")")"
echo -e "\t j = $(date +"%j") (day of the year)"
echo -e "\t u, w = $(date +"%u, %w") (day of the week)"
echo -e "Week"
echo -e "\t U, V, W = $(date +"%U, %V, %W")"
echo -e "Month"
echo -e "\t B = $(date +"%B (b/h = %b)")"
echo -e "\t m = $(date +"%m")"
echo -e "Year"
echo -e "\t Y = $(date +"%Y (y = %y)")"
echo -e "\t C = $(date +"%C") (century)" 
echo -e "\t G = $(date +"%G (g = %g)") (ISO week date)"
echo -e "Hour"
echo -e "\t H = $(date +"%H (k = \"%k\")")"
echo -e "\t I = $(date +"%I (l = \"%l\")")"
echo -e "\t P = $(date +"%P (p = %p)")"
echo -e "Minute"
echo -e "\t M = $(date +"%M")"
echo -e "Second"
echo -e "\t S = $(date +"%S")"
echo -e "Nanosecond"
echo -e "\t N = $(date +"%N")"
echo -e "Time zones"
echo -e "\t Z = $(date +"%Z")"
echo -e "\t z = $(date +"%z")"
echo -e "Useful shortcuts"
# Now
echo -e "\t c = $(date +"%c")"
# Date
echo -e "\t D = $(date +"%D")"
echo -e "\t F = $(date +"%F")"
# Time
echo -e "\t R = $(date +"%R")"
echo -e "\t T = $(date +"%T")"
# Local specific
echo -e "\t r = $(date +"%r")"
echo -e "\t x = $(date +"%x")"
echo -e "\t X = $(date +"%X")"
# Unix Time Stamp in seconds (1970-01-01)
echo -e "\t s = $(date +"%s") (UTC)"

