version: 1
formatters:
    my_formatter:
        format: '%(levelname)8s | %(name_last)s :: %(message)s'
handlers:
    my_handler:
        class: logging.StreamHandler
        formatter: my_formatter
        filters :
          - RecordAttributeAdder
        stream: ext://sys.stdout
loggers:
    LOG:
        level: INFO
        handlers: [my_handler]
        propogate: no
filters:
    RecordAttributeAdder:
      '()' : logger.RecordAttributeAdder
root:
    level: ERROR
    handlers: null
